name=input('Ваше имя:')
surname=input('Ваша фамилия:')
city=input('Ваш город:')
group=input('Ваша группа:')
age=int(input('Ваш возраст:'))
predmet=input('Ваш любимый предмет:')
vrem=float(input('Время подготовки в неделю:'))
print('Ваше имя и фамилия:', name, surname)
print('Ваш возраст через 4 года:', age+4)
print(f'Количество подготовки за 4 недели:{vrem*4:.2f}')
print(f'Среднее время подготовки: {vrem/7:.2f}')